import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserButton } from "@/components/UserButton";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <header className="bg-white z-50 fixed top-0 left-0 right-0 flex justify-between items-center py-3 px-12 border-b border-gray-200 h-16">
          <Link href="/">
            <span className="text-2xl font-bold">FluxContext</span>
          </Link>
          <UserButton />
        </header>
        <main className="pt-16 h-full">{children}</main>
      </body>
    </html>
  );
}
